### ISSUE TITLE
Front - TODO

### ISSUE THREAD

**Issue by LLxD** [roboforgeufu/roboforgeufu.github.io#1]
- [x] Atribuir JS para o botão do email

- [x] Corrigir os textos

- [x] Novo botão para cadastro no processo seletivo

- [x] Adicionar um slider com fotos da equipe na seção sobre nós

- [ ] Adicionar premiações

- [x] Pegar SVG da logo
